#!/usr/bin/env expect -f

set timeout -1
log_user 1
spawn valgrind --quiet --leak-check=full --error-exitcode=1 --exit-on-first-error=yes ./Minicoquillage
expect "\u001b\[?2004h\u001b\[1;34mtest\u001b\[0m via \ud83d\udc1a \u001b\[1;34m(Minicoquillage)\r\n"
send -- "echo \"\r"
expect "?2004h"
send -- "(\r"
expect "?2004h"
send -- "a\r"
expect "?2004h"
send -- "\"\r"
expect "\u001b\[?2004h\u001b\[1;34mtest\u001b\[0m via \ud83d\udc1a \u001b\[1;34m(Minicoquillage)\r\n"
send -- "echo \'\r"
expect "?2004h"
send -- "b\r"
expect "?2004h"
send -- "\'\r"
expect "\u001b\[?2004h\u001b\[1;34mtest\u001b\[0m via \ud83d\udc1a \u001b\[1;34m(Minicoquillage)\r\n"
send -- "echo \&&\r"
expect "?2004h"
send -- "echo\r"
expect "\u001b\[?2004h\u001b\[1;34mtest\u001b\[0m via \ud83d\udc1a \u001b\[1;34m(Minicoquillage)\r\n"
send -- "echo ||\r"
expect "?2004h"
send -- "echo\r"
expect "\u001b\[?2004h\u001b\[1;34mtest\u001b\[0m via \ud83d\udc1a \u001b\[1;34m(Minicoquillage)\r\n"
send -- "echo |\r"
expect "?2004h"
send -- "echo\r"
interact
expect eof
