#!/usr/bin/env expect -f

set timeaout -1
log_user 0
spawn valgrind --quiet --leak-check=full --error-exitcode=1 --exit-on-first-error=yes ./Minicoquillage
# Read lines from a file into a list
set fileId [open "./test/leak_test.csv" r]
set data [read $fileId]
close $fileId

# Convert data into a list (split on newlines)
set list [split $data "\n"]

# Iterate over the list
foreach item $list {
    expect "" 
    send -- "$item\n"
}
interact 
expect eof
