#!/usr/bin/env expect -f

set timeaout -1
log_user 0
spawn valgrind --quiet --track-origins=yes --leak-check=full\
--show-leak-kinds=all --suppressions=readline.supp\
--error-exitcode=1 --exit-on-first-error=yes ./minicoquillage
# Read lines from a file into a list
set fileId [open "./final_test/cmds_test.txt" r]
set data [read $fileId]
close $fileId

sleep 1
# Convert data into a list (split on newlines)
set list [split $data "\n"]

# Iterate over the list
foreach item $list {
    expect "" 
    send -- "$item\n"
}
interact 
expect eof
